### ISSUE TITLE
TypeError: i.advance is not a function

### ISSUE THREAD

**Issue by LawnCable** [luggage66/Sprache-js#1]
```
~/Documents/Projects/libconfig-parser-js/node_modules/sprache/dist/src/parse.js:317
                return result_1.Result.Success(i.current, i.advance());
                                                            ^

TypeError: i.advance is not a function
    at ~/Documents/Projects/libconfig-parser-js/node_modules/sprache/dist/src/parse.js:317:61
    at ~/Documents/Projects/libconfig-parser-js/node_modules/sprache/dist/src/parse.js:78:49
    at Object.identifier (~/Documents/Projects/libconfig-parser-js/node_modules/sprache/dist/src/parse.js:426:26)
    at Object.<anonymous> (~/Documents/Projects/libconfig-parser-js/src/test.js:11:12)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
```

**Comment by luggage66** [comment]
Can you provide some code to reproduce this error, please?

**Comment by LawnCable** [comment]
```
const { Parse } = require('sprache');
const identifier = Parse.query(function*() {
    const leading = yield Parse.whiteSpace.many();
    const first = yield Parse.letter.once();
    const rest = yield Parse.letterOrDigit.many();
    const trailing = yield Parse.whiteSpace.many();
    return Parse.return([first].concat(rest).join(''));
});
identifier("id2=5")
```
Using node v11.2.0

**Comment by luggage66** [comment]
Ahh. you need to use `identifier.parse("id2=5")` instead of `identifier("id2=5")`. Call .parse() or .tryParse() on the "parser". Calling the parser directly is meant for internal use.

**Comment by luggage66** [comment]
Also, here is a more full example to parse your text into an object:

```ts
        const AssignmentOperator = Parse.char('=', '= (assignment)');

        const Integer = Parse.digit.many().select(digits => {
            return Number.parseInt(digits.join(''), 10);
        }).token().named('an integer');

        const Identifier = Parse.query(function*() {
            const first = yield Parse.letter.once();
            const rest = yield Parse.letterOrDigit.many();
            return Parse.return([first].concat(rest).join(''));
        }).token();

        const AssignmentStatement = Parse.query(function*() {
            const identifier = yield Identifier;
            const assignmentOperator = yield AssignmentOperator;
            const value = yield Integer;

            return Parse.return({
                key: identifier,
                value: value,
            });
        });

        console.log("result:", AssignmentStatement.parse("id2=5"));
```

**Comment by LawnCable** [comment]
thanks, using .parse solved it; also thanks for the example.
